### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by Scofield-04-21-076** [aurora-is-near/evm2near#5]
```Solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.16;


contract Calc {

    function multiply(int ui) public returns (int) {

        return ui;
    }
}
```

After deploying this contract, I call the multiply method:
**near call name_contract.testnet multiply '{"ui": 16}' --accountId name_contract.testnet**

I get result: **'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10'**

Ideally, the expected result should be: **16**

But if you change the code as follows:
```Solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.16;


contract Calc {

    address public owner;
    uint256 public num;


    function multiply(int ui) public returns (int) {

        return ui;
    }
}
```

I get result: 
**Empty result ''**

Expected result: **16**

**Comment by birchmd** [comment]
@Scofield-04-21-076 Please pull the latest code and retry. The output is encoded nicely now, for example:

```
{ output: 16, status: 'SUCCESS' }
```

I also cannot reproduce your empty result issue.

Please include the commit you built the compiler from in future bug reports.
