### ISSUE TITLE
EVM Flashloan on Aurora. but get "A status code indicating if the top-level call succeeded or failed (applicable for Post BYZANTIUM blocks only)

### ISSUE THREAD

**Issue by cklai90** [aurora-is-near/evm2near#7]
I am had successfully deploy a flashloan contract on both Aurora & Aurora+ network (an EVM on Near protocol).

and also successfully tested with its RPC on hardhat, there are no issues, able to borrow and return fund.

However, when executing on mainnet, it shows a failed transaction with the following error:
"A status code indicating if the top-level call succeeded or failed (applicable for Post BYZANTIUM blocks only).

what could be the possible root cause?

**Comment by birchmd** [comment]
Hi @cklai90 , thanks for the report.

Just to be clear, this error was on Aurora and has nothing to do with the compiler project here? If the error is not related to this repository then please close the issue and open it on another one (e.g. `aurora-engine` or `aurora-relayer`). It would also be helpful if you post a transaction link (e.g. to aurorascan) as part of your bug report.

If this error is arising from a contract obtained from the compiler on this repository, could you please provide a link to the NEAR block explorer which shows the error?
